name: Lint Protos
on: 
  pull_request:
    branches:
      - main
  
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run protolint
        uses: plexsystems/protolint-action@v0.7.0
        with:
          configDirectory: ./