name: Build & Release

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build-descriptor:
    name: Build Proto Descriptor
    runs-on: ubuntu-latest
    outputs:
      descriptor_version: ${{ github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.SA_CREDENTIALS }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Build Descriptor
        run: |
          make descriptor

      - name: Upload Descriptor to Artifact Registry
        run: |
          gcloud artifacts generic upload \
            --project=${{ secrets.PROJECT_ID }} \
            --location=${{ secrets.GCP_REGION }} \
            --repository=${{ secrets.GAR_REPOSITORY }} \
            --package=protos \
            --version=${ GITHUB_SHA } \
            --source=gen/artifacts/desc.pb

  # rebuild-gateway:
  #   runs-on: ubuntu-latest
  #   needs: build-descriptor
  #   steps:
  #     - name: Trigger Docker workflow in another repository
  #       env:
  #         GH_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
  #         TARGET_REPO: your-org/docker-repo
  #         WORKFLOW_FILE: docker-build.yml
  #         REF: main
  #         VERSION: ${{ needs.build-binary.outputs.artifact_version }}
  #       run: |
  #         echo "Triggering $WORKFLOW_FILE in $TARGET_REPO with version=$VERSION"

  go-release:
    name: Release Go Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create tags
        run: |
          BASE_VERSION=${{ secrets.BASE_VERSION }}
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "TRACKING_TAG=${BASE_VERSION}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TRACKING_TAG }}
          name: "Release ${{ env.TRACKING_TAG }}"
          generate_release_notes: true